const mongoose = require("mongoose");
const Item = require("../models/Item");
const StockMovement = require("../models/StockMovement");

/**
 * Mathematically processes stock deltas between two sets of items and updates
 * the Item, its variants, and the StockMovement ledger atomically.
 *
 * @param {Object} params
 * @param {String} params.organization - Org ID
 * @param {String} params.documentId - Source document ID (Invoice, Purchase)
 * @param {String} params.documentModel - "Invoice", "Purchase", etc.
 * @param {String} params.documentNumber - Human readable document number
 * @param {Array} params.items - New items array
 * @param {Array} params.previousItems - Old items array (for delta on edits)
 * @param {String} params.baseDirection - "in" (purchases) or "out" (invoices)
 * @param {String} params.userId - ID of the user performing the action
 * @param {String} params.reason - Reason for movement (e.g. "sale", "purchase")
 * @param {Boolean} params.isReversal - If true, flips the base direction
 * @param {mongoose.ClientSession} params.session - Mongoose transaction session
 */
const syncDocumentStock = async ({
  organization,
  documentId,
  documentModel,
  documentNumber,
  items,
  previousItems = [],
  baseDirection,
  userId,
  reason,
  isReversal = false,
  session,
}) => {
  // Aggregate quantities by product/variant
  const itemDeltas = new Map(); // key: itemId|variantId, value: { itemId, variantId, deltaQuantity }

  // 1. Subtract previous items (to reverse their effect)
  for (const prev of previousItems) {
    if (!prev.itemId) continue;
    const key = `${prev.itemId}|${prev.variantId || "none"}`;
    if (!itemDeltas.has(key)) {
      itemDeltas.set(key, { itemId: prev.itemId, variantId: prev.variantId, deltaQuantity: 0 });
    }
    // If baseDirection is 'out', the original effect was negative. Reversing it means adding it back (+).
    // If baseDirection is 'in', original effect was positive. Reversing it means subtracting it (-).
    const flip = baseDirection === "out" ? 1 : -1;
    itemDeltas.get(key).deltaQuantity += (prev.quantity * flip);
  }

  // 2. Add new items
  for (const item of items) {
    if (!item.itemId) continue;
    const key = `${item.itemId}|${item.variantId || "none"}`;
    if (!itemDeltas.has(key)) {
      itemDeltas.set(key, { itemId: item.itemId, variantId: item.variantId, deltaQuantity: 0 });
    }
    // If baseDirection is 'out', effect is negative.
    // If baseDirection is 'in', effect is positive.
    const flip = baseDirection === "out" ? -1 : 1;
    itemDeltas.get(key).deltaQuantity += (item.quantity * flip);
  }

  // If this is a pure reversal (e.g. cancellation), we flip the entire result
  if (isReversal) {
    for (const [key, data] of itemDeltas.entries()) {
      data.deltaQuantity = data.deltaQuantity * -1;
    }
  }

  // 3. Process deltas
  for (const [key, data] of itemDeltas.entries()) {
    if (data.deltaQuantity === 0) continue;

    // Fetch the product inside the transaction
    const product = await Item.findOne({ _id: data.itemId, organization }).session(session);
    if (!product) continue;
    
    // Check if it tracks inventory
    if (product.type !== 'product' || !product.inventory.trackInventory) continue;

    const previousStock = product.inventory.currentStock;
    const newStock = previousStock + data.deltaQuantity;
    
    // Strict Insufficient Stock Check for Outgoing
    // (Only throw if the final computed stock is below zero and we are trying to deduct)
    if (newStock < 0 && data.deltaQuantity < 0) {
       throw new Error(`Insufficient stock for product: ${product.name}`);
    }

    // Update root level currentStock
    product.inventory.currentStock = newStock;
    product.inventory.lastMovementAt = new Date();

    // Update variant stock if applicable
    let variant = null;
    if (data.variantId) {
      variant = product.variants.id(data.variantId);
      if (variant) {
        // Just in case it wasn't tracking properly before, ensure it doesn't go below 0 on outgoing
        if ((variant.stock + data.deltaQuantity) < 0 && data.deltaQuantity < 0) {
            throw new Error(`Insufficient stock for variant of: ${product.name}`);
        }
        variant.stock += data.deltaQuantity;
      }
    }

    await product.save({ session, validateModifiedOnly: true });

    // 4. Create immutable StockMovement entry
    const direction = data.deltaQuantity > 0 ? "in" : "out";
    const absQuantity = Math.abs(data.deltaQuantity);

    const movement = new StockMovement({
      organization,
      item: product._id,
      variantId: variant ? variant._id : null,
      direction,
      quantity: absQuantity,
      previousStock,
      newStock,
      reason,
      notes: `Generated by ${documentModel} ${documentNumber}`,
      recordDate: new Date(),
      referenceNumber: documentNumber,
      // The variant's own purchase price when this movement is against a specific variant —
      // historical stock valuation must reflect what that variant actually cost, not the
      // parent's base price.
      unitPrice: (variant ? variant.purchasePrice : product.purchasePrice) || 0,
      user: userId,
    });

    await movement.save({ session });
  }
};

module.exports = {
  syncDocumentStock,
};
